<a href="https://colab.research.google.com/github/Skyy777/DAVIS/blob/main/1D_%26_2D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

A. 1D NumPy Array Questions

Write a program to create a 1D NumPy array with five elements entered by the user

In [2]:
import numpy as np
user_elements = []
for i in range(5):
    while True:
        try:
            element = float(input(f"Enter element {i+1}/5: "))
            user_elements.append(element)
            break
        except ValueError:
            print("Invalid input. Please enter a number.")
my_array = np.array(user_elements)
print("Your 1D NumPy array:")
print(my_array)

Enter element 1/5: 12
Enter element 2/5: 11
Enter element 3/5: 10
Enter element 4/5: 15
Enter element 5/5: 17
Your 1D NumPy array:
[12. 11. 10. 15. 17.]


Write a program to find the length of a 1D NumPy array

In [3]:
array_length = len(my_array)
print(f"The length of the NumPy array is: {array_length}")

The length of the NumPy array is: 5


Write a program to access the first, middle, and last element of a NumPy array

In [6]:
first_element = my_array[0]
print(f"First element: {first_element}")
last_element = my_array[-1]
print(f"Last element: {last_element}")
middle_index = array_length // 2
middle_element = my_array[middle_index]
print(f"Middle element: {middle_element}")

First element: 12.0
Last element: 17.0
Middle element: 10.0


Write a program to slice a NumPy array from index 2 to 5.

In [7]:
print(my_array[2:6])

[10. 15. 17.]


Write a program to print all elements of a NumPy array using a loop

In [8]:
print("Elements of the NumPy array using a loop:")
for element in my_array:
    print(element)

Elements of the NumPy array using a loop:
12.0
11.0
10.0
15.0
17.0


Write a program to add 10 to each element of a NumPy array

In [9]:
print(my_array + 10)

[22. 21. 20. 25. 27.]


Write a program to find the sum and average of elements in a 1D NumPy array.

In [10]:
print(f"Sum of elements: {np.sum(my_array)}")
print(f"Average of elements: {np.mean(my_array)}")

Sum of elements: 65.0
Average of elements: 13.0


Write a program to find the maximum and minimum value in a NumPy array.

In [11]:
print(f"Maximum value: {np.max(my_array)}")
print(f"Minimum value: {np.min(my_array)}")

Maximum value: 17.0
Minimum value: 10.0


Write a program to reverse a NumPy array using slicing.

In [12]:
print(my_array[::-1])

[17. 15. 10. 11. 12.]


Write a program to check whether a specific element exists in a NumPy array

In [13]:
search_element_input = input("Enter element: ")
try:
    search_element = float(search_element_input)
    if (my_array == search_element).any():
        print(f"The element {search_element} exists in the array.")
    else:
        print(f"The element {search_element} does not exist in the array.")
except ValueError:
    print("Invalid input. Please enter a number.")

Enter the element you want to check for: 11
The element 11.0 exists in the array.


 2D NumPy Array Questions

Write a program to create a 2D NumPy array of size 3×3 and display it.

In [15]:
import numpy as np
my_2d_array = np.array([[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]])

print("Your 2D NumPy array (3x3):")
print(my_2d_array)

Your 2D NumPy array (3x3):
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Write a program to find the shape of a 2D NumPy array.

In [16]:
array_shape = my_2d_array.shape
print(f"The shape of the 2D NumPy array is: {array_shape}")

The shape of the 2D NumPy array is: (3, 3)


Write a program to access a specific element from a 2D array using row and column index

In [18]:
try:
    row_index = int(input("Enter the row index (0-2): "))
    col_index = int(input("Enter the column index (0-2): "))
    if 0 <= row_index < my_2d_array.shape[0] and 0 <= col_index < my_2d_array.shape[1]:
        specific_element = my_2d_array[row_index, col_index]
        print(f"Element at row {row_index}, column {col_index}: {specific_element}")
    else:
        print("Error:")
except ValueError:
    print("Invalid input.")
except NameError:
    print("Error: 'my_2d_array' is not defined.")

Enter the row index (0-2): 1
Enter the column index (0-2): 2
Element at row 1, column 2: 6


Write a program to extract the first row and first column from a 2D NumPy array.

In [19]:
print("First row:", my_2d_array[0, :])
print("First column:", my_2d_array[:, 0])

First row: [1 2 3]
First column: [1 4 7]


Write a program to slice a 2D NumPy array to get a sub-matrix

In [25]:
sub_matrix = my_2d_array[0:2, 0:2]
print("Original 2D NumPy array:")
print(my_2d_array)
print("\nSub-matrix:")
print(sub_matrix)

Original 2D NumPy array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Sub-matrix:
[[1 2]
 [4 5]]


Write a program to calculate the sum of all elements in a 2D NumPy array

In [26]:
print(f"Sum of all elements: {np.sum(my_2d_array)}")

Sum of all elements: 45


Write a program to calculate row-wise sum of a 2D NumPy array

In [27]:
print(f"Row-wise sum: {np.sum(my_2d_array, axis=1)}")

Row-wise sum: [ 6 15 24]


Write a program to calculate column-wise average of a 2D NumPy array

In [28]:
print(f"column-wise average: {np.mean(my_2d_array, axis=0)}")

column-wise average: [4. 5. 6.]


Write a program to multiply each element of a 2D NumPy array by 2.

In [29]:
print(my_2d_array * 2)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


Write a program to find the maximum value from each row of a 2D NumPy array

In [30]:
print(f"Maximum value from each row: {np.max(my_2d_array, axis=1)}")

Maximum value from each row: [3 6 9]
