<a href="https://colab.research.google.com/github/Skyy777/DAVIS/blob/main/functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

power ()

In [3]:
import numpy as np
a = np.array([10,12,13,14,15])
print("our array is:")
print(a)
print("applying poower function")
print (np.power(a,2))

our array is:
[10 12 13 14 15]
applying poower function
[100 144 169 196 225]


round()
numpy.round(a, decimals=0, out=None)


In [10]:
print(np.round(a,decimals=5,out=None))

[10 12 13 14 15]


sqrt()

In [11]:
print(np.sqrt(a))

[3.16227766 3.46410162 3.60555128 3.74165739 3.87298335]
