<a href="https://colab.research.google.com/github/Skyy777/DAVIS/blob/main/Introduction_to_numpy_%26_slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Write a Python program to create a NumPy array with five integers and display it.
import numpy as np
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [2]:
#Write a program to find the data type of a NumPy array
a=np.array([1,2,3,4,4])
print(a.dtype)

int64


In [3]:
#Write a program to access the first and last element of a NumPy array

a=np.array([1,2,3,4,5])
print(a[0])
print(a[-1])

1
5


In [6]:
#Write a program to slice a NumPy array and print elements from index 1 to 3.

a=np.array([1,2,3,4,5])
print(a[0:3])

[1 2 3]


In [7]:
#Write a program to display the first three elements of a NumPy array using slicing

a=np.array([1,2,3,4,5])
print(a[:3])

[1 2 3]


In [8]:
#Write a program to extract the last two elements of a NumPy array using slicing

a=np.array([1,2,3,4,5])
print(a[-2:])

[4 5]
