<a href="https://colab.research.google.com/github/Skyy777/DAVIS/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


Slicing Syntax
array(startend)

In [3]:
print(arr[1:5])

[2 3 4 5]


In [4]:
print(arr[4:])

[ 5  6  7  8  9 10]


In [5]:
print(arr[:4])

[1 2 3 4]


In [6]:
print(arr[-3:-1])

[8 9]


In [7]:
print(arr[1:8:2])

[2 4 6 8]


Functions in Numpy

In [8]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [9]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr.dtype)

int64


In [10]:
arr = np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [11]:
arr = np.arange(1,11,2)
print(arr)

[1 3 5 7 9]


In [12]:
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [13]:
arr = np.ones(10)
print(arr)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [14]:
arr = np.full(10,5)
print(arr)

[5 5 5 5 5 5 5 5 5 5]


In [15]:
arr = np.random.rand(10)
print(arr)

[0.8438606  0.99155968 0.07641418 0.2588949  0.03842861 0.71576409
 0.55298145 0.05923616 0.43990324 0.72626997]


In [16]:
arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [17]:
arr = np.identity(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
marks = np.array([70,80,90,60])

print("sum:",np.sum(marks))
print("Average:",np.mean(marks))
print("Max:",np.max(marks))
print("min:",np.min(marks))

sum: 300
Average: 75.0
Max: 90
min: 60
