<a href="https://colab.research.google.com/github/Skyy777/DAVIS/blob/main/Numpy_function.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

You are given a NumPy array of student marks. Write a program to extract marks greater than the class average.

In [2]:
import numpy as np
marks = np.array([75, 82, 90, 65, 88, 70, 95, 78])
class_average = np.mean(marks)
print(f"Original marks: {marks}")
print(f"Class average: {class_average:.2f}")
marks_above_average = marks[marks > class_average]
print(f"Marks greater than the class average: {marks_above_average}")

Original marks: [75 82 90 65 88 70 95 78]
Class average: 80.38
Marks greater than the class average: [82 90 88 95]




A company stores daily sales data in a NumPy array. Write a program to find days where sales were higher than 50,000


In [5]:
sales_data = np.array([45000, 52000, 48000, 60000, 39000, 55000, 51000])
print(f"Original sales data: {sales_data}")
high_sales_days = sales_data[sales_data > 50000]
print(f"Days with sales higher than 50,000: {high_sales_days}")

Original sales data: [45000 52000 48000 60000 39000 55000 51000]
Days with sales higher than 50,000: [52000 60000 55000 51000]


Given a NumPy array of temperatures in Celsius, write a program to convert all values to Fahrenheit using vectorized operations.

In [19]:
celsius_temps = np.array([0, 10, 20, 25, 30, 37, 100])
print(f"Original Celsius temperatures: {celsius_temps}")
fahrenheit_temps = celsius_temps * 9/5 + 32
print(f"Converted Fahrenheit temperatures: {fahrenheit_temps}")

Original Celsius temperatures: [  0  10  20  25  30  37 100]
Converted Fahrenheit temperatures: [ 32.   50.   68.   77.   86.   98.6 212. ]


A NumPy array contains employee working hours for a week. Write a program to find employees who worked more than 40 hours

In [22]:
working_hours = np.array([38, 45, 40, 52, 35, 41, 48])
print(f"Original employee working hours: {working_hours}")
employees_over_40_hours = working_hours[working_hours > 40]
print(f"Employees who worked more than 40 hours: {employees_over_40_hours}")

Original employee working hours: [38 45 40 52 35 41 48]
Employees who worked more than 40 hours: [45 52 41 48]


Given a NumPy array of product prices, write a program to apply a 10 percent discount on prices greater than 1,000

In [11]:
product_prices = np.array([500, 1200, 800, 1500, 950, 2000, 1100])
print(f"Original product prices: {product_prices}")
high_price_mask = product_prices > 1000
product_prices[high_price_mask] = product_prices[high_price_mask] * 0.90
print(f"Product prices after 10% discount on prices > 1,000: {product_prices}")

Original product prices: [ 500 1200  800 1500  950 2000 1100]
Product prices after 10% discount on prices > 1,000: [ 500 1080  800 1350  950 1800  990]


A NumPy array contains exam scores. Write a program to replace all scores below 35 with 35 using NumPy operations

In [13]:
exam_scores = np.array([40, 25, 78, 30, 92, 15, 60, 35])
print(f"Original exam scores: {exam_scores}")
exam_scores[exam_scores < 35] = 35
print(f"Exam scores after replacing values below 35 with 35: {exam_scores}")

Original exam scores: [40 25 78 30 92 15 60 35]
Exam scores after replacing values below 35 with 35: [40 35 78 35 92 35 60 35]


Given a 2D NumPy array representing marks of students in multiple subjects, write a program to calculate student-wise average marks

In [15]:
student_marks = np.array([
    [85, 90, 78, 92],
    [70, 65, 80, 75],
    [95, 88, 91, 87],
    [60, 72, 68, 70]
])
print(f"Original student marks:\n{student_marks}")
student_average_marks = np.mean(student_marks, axis=1)
print(f"\nStudent-wise average marks: {student_average_marks}")

Original student marks:
[[85 90 78 92]
 [70 65 80 75]
 [95 88 91 87]
 [60 72 68 70]]

Student-wise average marks: [86.25 72.5  90.25 67.5 ]


A NumPy array contains monthly expenses. Write a program to identify expenses that are above the median value

In [17]:
monthl_expenses = np.array([1500, 2000, 1800, 2200,2500])
print(f"Original monthly expenses: {monthl_expenses}")
median_expense = np.median(monthl_expenses)
print(f"Median expense: {median_expense}")
above_median_expenses = monthl_expenses[monthl_expenses > median_expense]
print(f"Expenses above the median value: {above_median_expenses}")

Original monthly expenses: [1500 2000 1800 2200 2500]
Median expense: 2000.0
Expenses above the median value: [2200 2500]


Hard Level Questions (Interview + Industry Thinking)


A 2D NumPy array represents sales data of products across different regions. Write a program to find the region with the highest total sales.

In [23]:
sales_data = np.array([
    [100, 150, 120, 200],
    [130, 110, 180, 160],
    [210, 90, 140, 170],
    [180, 220, 100, 190]
])
print(f"Original sales data (regions x products):\n{sales_data}")
total_sales_per_region = np.sum(sales_data, axis=1)
print(f"\nTotal sales per region: {total_sales_per_region}")
highest_sales_region_index = np.argmax(total_sales_per_region)
highest_sales_region_number = highest_sales_region_index + 1
print(f"Region with the highest total sales: Region {highest_sales_region_number} (Total Sales: {total_sales_per_region[highest_sales_region_index]})")

Original sales data (regions x products):
[[100 150 120 200]
 [130 110 180 160]
 [210  90 140 170]
 [180 220 100 190]]

Total sales per region: [570 580 610 690]
Region with the highest total sales: Region 4 (Total Sales: 690)


Given a NumPy array of sensor readings, write a program to detect and extract all abnormal readings that are more than 2 times the mean value.

In [25]:
sensor_readings = np.array([10, 12, 11, 15, 100, 13, 14, 12, 200, 16])
print(f"Original sensor readings: {sensor_readings}")
mean_value = np.mean(sensor_readings)
print(f"Mean value: {mean_value:.2f}")
abnormal_threshold = 2 * mean_value
print(f"Abnormal threshold (2 * mean): {abnormal_threshold:.2f}")
abnormal_readings = sensor_readings[sensor_readings > abnormal_threshold]
print(f"Abnormal readings (more than 2 times the mean): {abnormal_readings}")

Original sensor readings: [ 10  12  11  15 100  13  14  12 200  16]
Mean value: 40.30
Abnormal threshold (2 * mean): 80.60
Abnormal readings (more than 2 times the mean): [100 200]


A NumPy array contains salary data of employees. Write a program to apply tax rules:


Salary above 50,000 → deduct 10 percent


Salary above 1,00,000 → deduct 20 percent


In [27]:
salary_data = np.array([40000, 70000, 120000, 50000, 100000, 150000, 60000, 25000])
print(f"Original salary data: {salary_data}")
modified_salaries = salary_data.copy().astype(float)
mask_20_percent = salary_data > 100000
modified_salaries[mask_20_percent] = salary_data[mask_20_percent] * 0.80
mask_10_percent = (salary_data > 50000) & (salary_data <= 100000)
modified_salaries[mask_10_percent] = salary_data[mask_10_percent] * 0.90
mask_5_percent = salary_data <= 50000
modified_salaries[mask_5_percent] = salary_data[mask_5_percent] * 0.95
print(f"Salary data after tax deductions: {modified_salaries}")

Original salary data: [ 40000  70000 120000  50000 100000 150000  60000  25000]
Salary data after tax deductions: [ 38000.  63000.  96000.  47500.  90000. 120000.  54000.  23750.]


Given a 2D NumPy array of student marks, write a program to find how many students failed in each subject.

In [31]:
student_marks = np.array([
    [85, 90, 78, 92],
    [70, 65, 35, 28],
    [95, 88, 91, 87],
    [60, 30, 68, 70]
])
print(f"Original student marks:\n{student_marks}")
passing_score = 35
failed_students_per_subject = np.sum(student_marks < passing_score, axis=0)
print(f"\nNumber of students failed in each subject: {failed_students_per_subject}")

Original student marks:
[[85 90 78 92]
 [70 65 35 28]
 [95 88 91 87]
 [60 30 68 70]]

Number of students failed in each subject: [0 1 0 1]


A NumPy array contains website response times in milliseconds. Write a program to count how many requests exceeded the acceptable threshold.

In [33]:
response_times = np.array([120, 250, 80, 300, 150, 400, 90, 200, 500])
acceptable_threshold = 200
print(f"Original response times: {response_times}")
print(f"Acceptable threshold: {acceptable_threshold} ms")
requests_exceeded_threshold = np.sum(response_times > acceptable_threshold)
print(f"Number of requests that exceeded the acceptable threshold: {requests_exceeded_threshold}")

Original response times: [120 250  80 300 150 400  90 200 500]
Acceptable threshold: 200 ms
Number of requests that exceeded the acceptable threshold: 4


Given a NumPy array of daily profit and loss values, write a program to separate profit days and loss days using boolean indexing.

In [40]:
daily_values = np.array([150, -50, 250, -70, 200, 350, -100, 400, -500, 150])
print(f"Original daily values: {daily_values}")
profit_days = daily_values[daily_values > 0]
loss_days = daily_values[daily_values < 0]
print(f"Profit days: {profit_days}")
print(f"Loss days: {loss_days}")


print(f"Total profit: {profit_days.sum()}")
print(f"Total loss: {loss_days.sum()}")
print(f"Average profit: {profit_days.mean()}")
print(f"Average loss: {loss_days.mean()}")

Original daily values: [ 150  -50  250  -70  200  350 -100  400 -500  150]
Profit days: [150 250 200 350 400 150]
Loss days: [ -50  -70 -100 -500]
Total profit: 1500
Total loss: -720
Average profit: 250.0
Average loss: -180.0


A 2D NumPy array represents attendance of employees where 1 means present and 0 means absent. Write a program to calculate attendance percentage of each employee

In [42]:
attendance_data = np.array([
    [1, 1, 0, 1, 1],
    [0, 1, 1, 0, 0],
    [1, 1, 1, 1, 1],
    [0, 0, 0, 1, 1]])
persentage_attendance = np.mean(attendance_data, axis=0) * 100
print(f"Attendance percentage of each employee:\n{persentage_attendance}")

Attendance percentage of each employee:
[50. 75. 50. 75. 75.]


A NumPy array contains ratings given by users. Write a program to normalize the ratings between 0 and 1

In [44]:
ratings = np.array([4, 3, 5, 2, 4, 3, 5])
print(f"Original ratings: {ratings}")
min_rating = np.min(ratings)
max_rating = np.max(ratings)
if max_rating == min_rating:
    normalized_ratings = np.zeros_like(ratings)
else:
    normalized_ratings = (ratings - min_rating) / (max_rating - min_rating)
print(f"Normalized ratings between 0 and 1: {normalized_ratings}")

Original ratings: [4 3 5 2 4 3 5]
Normalized ratings between 0 and 1: [0.66666667 0.33333333 1.         0.         0.66666667 0.33333333
 1.        ]


Given a NumPy array of transaction amounts, write a program to flag suspicious transactions that are either extremely low or extremely high

In [49]:
transaction_amounts = np.array([100, 150, 200, 50, 5000, 120, 180, 20, 7000, 250])
print(f"Original transaction amounts: {transaction_amounts}")
std_dev_amount = np.std(transaction_amounts)
lower_threshold = mean_amount - 2 * std_dev_amount
upper_threshold = mean_amount + 2 * std_dev_amount
print(f"Lower suspicious threshold: {lower_threshold:.2f}")
print(f"Upper suspicious threshold: {upper_threshold:.2f}")
suspicious_transactions = transaction_amounts[
    (transaction_amounts < lower_threshold) | (transaction_amounts > upper_threshold)
]
print(f"Suspicious transactions (extremely low or high): {suspicious_transactions}")

Original transaction amounts: [ 100  150  200   50 5000  120  180   20 7000  250]
Lower suspicious threshold: -3472.21
Upper suspicious threshold: 6086.21
Suspicious transactions (extremely low or high): [7000]


A 2D NumPy array stores marks of students across tests. Write a program to identify the topper based on total marks.

In [54]:
test_marks = np.array([[70,30,50,56,50],
                      [50,55,56,67,87],
                       [68,46,65,45,67],
                        [555,44,35,46,76]])
print(f"Original test marks:\n{test_marks}")
total_marks_per_student = np.sum(test_marks, axis=1)
topper_index = np.argmax(total_marks_per_student)
topper_marks = total_marks_per_student[topper_index]
print(f"Topper marks: {topper_marks}")
print(f"Topper index: {topper_index}")

Original test marks:
[[ 70  30  50  56  50]
 [ 50  55  56  67  87]
 [ 68  46  65  45  67]
 [555  44  35  46  76]]
Topper marks: 756
Topper index: 3
