<a href="https://colab.research.google.com/github/Skyy777/DAVIS/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy

In [ ]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


Slicing Syntax
array(startend)

In [ ]:
print(arr[1:5])

[2 3 4 5]


In [ ]:
print(arr[4:])

[ 5  6  7  8  9 10]


In [ ]:
print(arr[:4])

[1 2 3 4]


In [ ]:
print(arr[-3:-1])

[8 9]


In [ ]:
print(arr[1:8:2])

[2 4 6 8]


Functions in Numpy

In [ ]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr.dtype)

int64


In [ ]:
arr = np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
arr = np.arange(1,11,2)
print(arr)

[1 3 5 7 9]


In [ ]:
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
arr = np.ones(10)
print(arr)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
arr = np.full(10,5)
print(arr)

[5 5 5 5 5 5 5 5 5 5]


In [ ]:
arr = np.random.rand(10)
print(arr)

[0.8438606  0.99155968 0.07641418 0.2588949  0.03842861 0.71576409
 0.55298145 0.05923616 0.43990324 0.72626997]


In [ ]:
arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
arr = np.identity(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
marks = np.array([70,80,90,60])

print("sum:",np.sum(marks))
print("Average:",np.mean(marks))
print("Max:",np.max(marks))
print("min:",np.min(marks))

sum: 300
Average: 75.0
Max: 90
min: 60


2D Numpy array

In [ ]:
arr = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])
print(arr)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [ ]:
print(arr.shape)

(3, 3)


2d Array accessing Elements
array[row_index,coloum_index

In [ ]:
print(arr[0,1])

20


In [ ]:
print(arr[2,1])

80


In [ ]:
print(arr[0:3,0:2])

[[10 20]
 [40 50]
 [70 80]]


In [ ]:
print(arr[1:3,1:3])

[[50 60]
 [80 90]]


In [2]:
import numpy as np
arr = np.array([
    [10,20,30,11],
    [40,50,60,21],
    [70,80,90,31]
])
print(arr)

[[10 20 30 11]
 [40 50 60 21]
 [70 80 90 31]]


In [18]:
print(arr[1:3,1:4])

[[50 60 21]
 [80 90 31]]


In [19]:
print(arr[0:2,1:3])

[[20 30]
 [50 60]]


In [20]:
print(arr[1:3,2:4])

[[60 21]
 [90 31]]


In [21]:
print(arr[1:3,1:3])

[[50 60]
 [80 90]]


In [22]:
print("average marks:", np.mean(arr))

average marks: 42.75


In [23]:
print("average marks :",np.mean(arr,axis=0))

average marks : [40. 50. 60. 21.]


In [24]:
print("average marks :",np.mean(arr,axis=1))

average marks : [17.75 42.75 67.75]


In [25]:
print("max marks :",np.max(arr))

max marks : 90
