<a href="https://colab.research.google.com/github/Skyy777/DAVIS/blob/main/Numpy_function.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

You are given a NumPy array of student marks. Write a program to extract marks greater than the class average.

In [2]:
import numpy as np
marks = np.array([75, 82, 90, 65, 88, 70, 95, 78])
class_average = np.mean(marks)
print(f"Original marks: {marks}")
print(f"Class average: {class_average:.2f}")
marks_above_average = marks[marks > class_average]
print(f"Marks greater than the class average: {marks_above_average}")

Original marks: [75 82 90 65 88 70 95 78]
Class average: 80.38
Marks greater than the class average: [82 90 88 95]




A company stores daily sales data in a NumPy array. Write a program to find days where sales were higher than 50,000


In [5]:
sales_data = np.array([45000, 52000, 48000, 60000, 39000, 55000, 51000])
print(f"Original sales data: {sales_data}")
high_sales_days = sales_data[sales_data > 50000]
print(f"Days with sales higher than 50,000: {high_sales_days}")

Original sales data: [45000 52000 48000 60000 39000 55000 51000]
Days with sales higher than 50,000: [52000 60000 55000 51000]


Given a NumPy array of temperatures in Celsius, write a program to convert all values to Fahrenheit using vectorized operations.

In [19]:
celsius_temps = np.array([0, 10, 20, 25, 30, 37, 100])
print(f"Original Celsius temperatures: {celsius_temps}")
fahrenheit_temps = celsius_temps * 9/5 + 32
print(f"Converted Fahrenheit temperatures: {fahrenheit_temps}")

Original Celsius temperatures: [  0  10  20  25  30  37 100]
Converted Fahrenheit temperatures: [ 32.   50.   68.   77.   86.   98.6 212. ]


A NumPy array contains employee working hours for a week. Write a program to find employees who worked more than 40 hours

In [22]:
working_hours = np.array([38, 45, 40, 52, 35, 41, 48])
print(f"Original employee working hours: {working_hours}")
employees_over_40_hours = working_hours[working_hours > 40]
print(f"Employees who worked more than 40 hours: {employees_over_40_hours}")

Original employee working hours: [38 45 40 52 35 41 48]
Employees who worked more than 40 hours: [45 52 41 48]


Given a NumPy array of product prices, write a program to apply a 10 percent discount on prices greater than 1,000

In [11]:
product_prices = np.array([500, 1200, 800, 1500, 950, 2000, 1100])
print(f"Original product prices: {product_prices}")
high_price_mask = product_prices > 1000
product_prices[high_price_mask] = product_prices[high_price_mask] * 0.90
print(f"Product prices after 10% discount on prices > 1,000: {product_prices}")

Original product prices: [ 500 1200  800 1500  950 2000 1100]
Product prices after 10% discount on prices > 1,000: [ 500 1080  800 1350  950 1800  990]


A NumPy array contains exam scores. Write a program to replace all scores below 35 with 35 using NumPy operations

In [13]:
exam_scores = np.array([40, 25, 78, 30, 92, 15, 60, 35])
print(f"Original exam scores: {exam_scores}")
exam_scores[exam_scores < 35] = 35
print(f"Exam scores after replacing values below 35 with 35: {exam_scores}")

Original exam scores: [40 25 78 30 92 15 60 35]
Exam scores after replacing values below 35 with 35: [40 35 78 35 92 35 60 35]


Given a 2D NumPy array representing marks of students in multiple subjects, write a program to calculate student-wise average marks

In [15]:
student_marks = np.array([
    [85, 90, 78, 92],
    [70, 65, 80, 75],
    [95, 88, 91, 87],
    [60, 72, 68, 70]
])
print(f"Original student marks:\n{student_marks}")
student_average_marks = np.mean(student_marks, axis=1)
print(f"\nStudent-wise average marks: {student_average_marks}")

Original student marks:
[[85 90 78 92]
 [70 65 80 75]
 [95 88 91 87]
 [60 72 68 70]]

Student-wise average marks: [86.25 72.5  90.25 67.5 ]


A NumPy array contains monthly expenses. Write a program to identify expenses that are above the median value

In [17]:
monthl_expenses = np.array([1500, 2000, 1800, 2200,2500])
print(f"Original monthly expenses: {monthl_expenses}")
median_expense = np.median(monthl_expenses)
print(f"Median expense: {median_expense}")
above_median_expenses = monthl_expenses[monthl_expenses > median_expense]
print(f"Expenses above the median value: {above_median_expenses}")

Original monthly expenses: [1500 2000 1800 2200 2500]
Median expense: 2000.0
Expenses above the median value: [2200 2500]


Hard Level Questions (Interview + Industry Thinking)


A 2D NumPy array represents sales data of products across different regions. Write a program to find the region with the highest total sales.

In [23]:
sales_data = np.array([
    [100, 150, 120, 200],
    [130, 110, 180, 160],
    [210, 90, 140, 170],
    [180, 220, 100, 190]
])
print(f"Original sales data (regions x products):\n{sales_data}")
total_sales_per_region = np.sum(sales_data, axis=1)
print(f"\nTotal sales per region: {total_sales_per_region}")
highest_sales_region_index = np.argmax(total_sales_per_region)
highest_sales_region_number = highest_sales_region_index + 1
print(f"Region with the highest total sales: Region {highest_sales_region_number} (Total Sales: {total_sales_per_region[highest_sales_region_index]})")

Original sales data (regions x products):
[[100 150 120 200]
 [130 110 180 160]
 [210  90 140 170]
 [180 220 100 190]]

Total sales per region: [570 580 610 690]
Region with the highest total sales: Region 4 (Total Sales: 690)
