Indexing & Slicing


In [1]:
import  numpy as np
a= np.arange(10)
s= slice(2,7,2)
print (a[s])

[2 4 6]


In [2]:
a= np.arange(10)
b= a[2:7:2]
print(b)

[2 4 6]


In [3]:
#slice single item
a= np.arange(10)
b= a[5]
print(b)

5


In [6]:
#slice items starting from index
a= np.arange(10)
print(a[2:])

[2 3 4 5 6 7 8 9]


In [7]:
#slice items between indexes
a= np.arange(10)
print(a[2:5])

[2 3 4]


In [10]:
a= np.array([[1,2,3],[3,4,5],[4,5,6]])
print(a)
print(a[1:])

[[1 2 3]
 [3 4 5]
 [4 5 6]]
[[3 4 5]
 [4 5 6]]


In [11]:
a= np.array([[1,2,3],[3,4,5],[4,5,6]])
print(a)
print('\n')
print(a[...,1])
print(a[1,...])
print('\n')
print(a[...,1:])

[[1 2 3]
 [3 4 5]
 [4 5 6]]


[2 4 5]
[3 4 5]


[[2 3]
 [4 5]
 [5 6]]


Advance indexing

In [12]:
#Integer indexing
x = np.array([[1, 2], [3, 4], [5, 6]])
y = x[[0,1,2], [0,1,0]]
print(y)

[1 4 5]


In [14]:
x= np.array([[0,1,2],
             [3,4,5],
             [6,7,8],
             [9,10,11]])
print(x)
print('\n')
rows = np.array([[0,0],[3,3]])
cols = np.array([[0,2],[0,2]])
y = x[rows,cols]
print(y)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


[[ 0  2]
 [ 9 11]]


In [15]:
#Boolean array indexing
x=np.array([[0,1,2],
            [3,4,5],
            [6,7,8],
            [9,10,11]])
print(x)
print('\n')
print(x[x>5])

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


[ 6  7  8  9 10 11]


In [16]:
a= np.array([np.nan,1,2,np.nan,3,4,5])
print(a[~np.isnan(a)])

[1. 2. 3. 4. 5.]


In [17]:
a= np.array([1,2+6j,5,3.5+5j])
print(a[np.iscomplex(a)])

[2. +6.j 3.5+5.j]


In [18]:
#Broadcasting
a= np.array([1,2,3,4])
b= np.array([10,20,30,40])
c= a*b
print(c)

[ 10  40  90 160]


In [19]:
a= np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]])
b= np.array([1.0,2.0,3.0])
print(a)
print('\n')
print(b)
print('\n')
print(a+b)

[[ 0.  0.  0.]
 [10. 10. 10.]
 [20. 20. 20.]
 [30. 30. 30.]]


[1. 2. 3.]


[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


iterating over array

In [20]:
a=np.arange(0,60,5)
a= a.reshape(3,4)
print(a)
print('\n')
for x in np.nditer(a):
  print(x,end=" ")
print('\n')

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


0 5 10 15 20 25 30 35 40 45 50 55 



In [22]:
a=np.arange(0,60,5)
a=a.reshape(3,4)
print(a)
print('\n')
b=a.T
print(b)
print('\n')
for x in np.nditer(b):
  print(x)

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]


0
5
10
15
20
25
30
35
40
45
50
55


In [23]:
# Iteration Order
a=np.arange(0,60,5)
a=a.reshape(3,4)
print(a)
print('\n')
b=a.T
print(b)
print('\n')
c=b.copy(order='C')
print(c)
print('\n')
for x in np.nditer(c):
  print(x)
print('\n')
c=b.copy(order='F')
print(c)
print('\n')
for x in np.nditer(c):
  print(x)

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]


[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]


0
20
40
5
25
45
10
30
50
15
35
55


[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]


0
5
10
15
20
25
30
35
40
45
50
55


Concatenate

In [24]:
a=np.array([[1,2],[3,4]])
print(a)
print('\n')
b=np.array([[5,6],[7,8]])
print(b)
print('\n')
print(np.concatenate((a,b)))

[[1 2]
 [3 4]]


[[5 6]
 [7 8]]


[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [25]:
#Split
a=np.arange(9)
print(a)
print('\n')
b=np.split(a,3)
print(b)
print('\n')
c=np.split(a,[4,7])
print(c)
print('\n')

[0 1 2 3 4 5 6 7 8]


[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8])]




In [26]:
#resize
a=np.array([[1,2,3],[4,5,6]])
print(a)
print('\n')
print(np.resize(a,(3,2)))
print('\n')
print(np.resize(a,(4,3)))

[[1 2 3]
 [4 5 6]]


[[1 2]
 [3 4]
 [5 6]]


[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


Arithmetic operations

In [28]:
a=np.arange(9,dtype=np.float64).reshape(3,3)
print(a)
b=np.array([10,10,10])
print(b)
print('\n')
print (np.add(a,b))
print('\n')
print(np.subtract(a,b))
print('\n')
print(np.multiply(a,b))
print('\n')
print(np.divide(a,b))

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
[10 10 10]


[[10. 11. 12.]
 [13. 14. 15.]
 [16. 17. 18.]]


[[-10.  -9.  -8.]
 [ -7.  -6.  -5.]
 [ -4.  -3.  -2.]]


[[ 0. 10. 20.]
 [30. 40. 50.]
 [60. 70. 80.]]


[[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]]


In [29]:
#power
a=np.array([0,1,2])
print(a)
print('\n')
print(np.power(a,2))
print('\n')

[0 1 2]


[0 1 4]




In [30]:
#mod
a=np.array([10,20,30])
b=np.array([3,5,7])
print(a)
print('\n')
print(b)
print('\n')
print(np.mod(a,b))
print('\n')
print(np.remainder(a,b))

[10 20 30]


[3 5 7]


[1 0 2]


[1 0 2]


In [31]:
#sort
a=np.array([[3,7],[9,1]])
print(a)
print('\n')
print(np.sort(a))
print('\n')
print(np.sort(a,axis=0))

[[3 7]
 [9 1]]


[[3 7]
 [1 9]]


[[3 1]
 [9 7]]


In [34]:
a=np.array([[3,7],[9,1]])
print(a)
print('\n')
print(np.sort(a))
print('\n')
print(np.sort(a,axis=0))
print('\n')
dt=np.dtype([('name','S10'),('age','int8'),('marks','float64')])
a=np.array([("raju",21),("anil",17),("amar",27),("ravi",17)],dtype=dt)
print(a)
print('\n')
print(np.sort(a,order='name'))

[[3 7]
 [9 1]]


[[3 7]
 [1 9]]


[[3 1]
 [9 7]]




ValueError: could not assign tuple of length 2 to structure with 3 fields.