<a href="https://colab.research.google.com/github/Skyy777/DAVIS/blob/main/SSELF_SOLVED_EXAMPLES.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Indexing & Slicing


In [1]:
import  numpy as np
a= np.arange(10)
s= slice(2,7,2)
print (a[s])

[2 4 6]


In [2]:
a= np.arange(10)
b= a[2:7:2]
print(b)

[2 4 6]


In [3]:
#slice single item
a= np.arange(10)
b= a[5]
print(b)

5


In [6]:
#slice items starting from index
a= np.arange(10)
print(a[2:])

[2 3 4 5 6 7 8 9]


In [7]:
#slice items between indexes
a= np.arange(10)
print(a[2:5])

[2 3 4]


In [10]:
a= np.array([[1,2,3],[3,4,5],[4,5,6]])
print(a)
print(a[1:])

[[1 2 3]
 [3 4 5]
 [4 5 6]]
[[3 4 5]
 [4 5 6]]


In [11]:
a= np.array([[1,2,3],[3,4,5],[4,5,6]])
print(a)
print('\n')
print(a[...,1])
print(a[1,...])
print('\n')
print(a[...,1:])

[[1 2 3]
 [3 4 5]
 [4 5 6]]


[2 4 5]
[3 4 5]


[[2 3]
 [4 5]
 [5 6]]


Advance indexing

In [12]:
#Integer indexing
x = np.array([[1, 2], [3, 4], [5, 6]])
y = x[[0,1,2], [0,1,0]]
print(y)

[1 4 5]


In [14]:
x= np.array([[0,1,2],
             [3,4,5],
             [6,7,8],
             [9,10,11]])
print(x)
print('\n')
rows = np.array([[0,0],[3,3]])
cols = np.array([[0,2],[0,2]])
y = x[rows,cols]
print(y)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


[[ 0  2]
 [ 9 11]]


In [15]:
#Boolean array indexing
x=np.array([[0,1,2],
            [3,4,5],
            [6,7,8],
            [9,10,11]])
print(x)
print('\n')
print(x[x>5])

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


[ 6  7  8  9 10 11]


In [16]:
a= np.array([np.nan,1,2,np.nan,3,4,5])
print(a[~np.isnan(a)])

[1. 2. 3. 4. 5.]


In [17]:
a= np.array([1,2+6j,5,3.5+5j])
print(a[np.iscomplex(a)])

[2. +6.j 3.5+5.j]
